# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 07:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotelName', models.CharField(max_length=20)),
                ('hotelIntro', models.TextField(blank=True, default='')),
                ('city', models.CharField(max_length=20)),
                ('district', models.CharField(max_length=20)),
                ('detailedAddress', models.CharField(blank=True, default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomID', models.PositiveIntegerField()),
                ('roomStatus', models.CharField(choices=[('F', 'FREE'), ('U', 'USING'), ('M', 'UNDER_MAINTENANCE')], default='F', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TypeName', models.CharField(max_length=20)),
                ('price', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, default='')),
                ('hotelName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Hotel')),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='TypeName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.RoomType'),
        ),
        migrations.AddField(
            model_name='room',
            name='hotelName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Hotel'),
        ),
        migrations.AlterUniqueTogether(
            name='roomtype',
            unique_together=set([('TypeName', 'hotelName')]),
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together=set([('roomID', 'hotelName')]),
        ),
    ]
