# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 08:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_customerprofile_hotelmanagerprofile_hotelreceptionprofile'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customerprofile',
            table='CustomerUser',
        ),
        migrations.AlterModelTable(
            name='hotelmanagerprofile',
            table='HotelManagerUser',
        ),
        migrations.AlterModelTable(
            name='hotelreceptionprofile',
            table=' HotelReceptionUser',
        ),
    ]
