# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 09:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170914_0842'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingRoom',
            fields=[
                ('BookingID', models.AutoField(primary_key=True, serialize=False)),
                ('bookingTime', models.DateTimeField(auto_now_add=True)),
                ('bookingNum', models.PositiveIntegerField()),
                ('TypeName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.RoomType')),
            ],
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('checkInID', models.AutoField(primary_key=True, serialize=False)),
                ('checkInTime', models.DateTimeField(auto_now_add=True)),
                ('leaveTime', models.DateTimeField()),
                ('customerName', models.CharField(max_length=20)),
                ('customerPhoneNumber', models.CharField(max_length=20)),
                ('customerIDCard', models.CharField(max_length=18)),
                ('status', models.CharField(choices=[('C', 'CHECKED_IN'), ('L', 'LEAVED')], default='C', max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='id',
        ),
        migrations.RemoveField(
            model_name='hotelmanagerprofile',
            name='id',
        ),
        migrations.RemoveField(
            model_name='hotelreceptionprofile',
            name='id',
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hotelmanagerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hotelreceptionprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='checkin',
            name='customerUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.CustomerProfile'),
        ),
        migrations.AddField(
            model_name='checkin',
            name='hotelName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Hotel'),
        ),
        migrations.AddField(
            model_name='checkin',
            name='roomID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Room'),
        ),
        migrations.AddField(
            model_name='bookingroom',
            name='customerUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.CustomerProfile'),
        ),
        migrations.AddField(
            model_name='bookingroom',
            name='hotelName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Hotel'),
        ),
    ]
