# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20170914_0900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='id',
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotelName',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
