# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 03:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20170918_0833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='TypeName',
            new_name='type',
        ),
    ]
