# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 02:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20170920_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='leaveTime',
            field=models.DateTimeField(null=True),
        ),
    ]
